### ISSUE TITLE
Pull container image

### ISSUE THREAD

**Issue by NicolasGlassey** [AMT-TEAM01/Main#1]
@JanisChiffelle  @tomicmario 

Messieurs,

Je suis en train d'évaluer votre livrable. Il m'est impossible de récupérer votre image, malgré les premières étapes de votre documentation réalisées avec succès.

Voici où j'en suis :

* Login via command line to the image registry

```
echo %CR_PAT% | docker login ghrc.io -u nicolas.glassey@cpnv.ch --password-stdin
Login Succeeded
```

* Try to pull docker image

```
docker pull ghcr.io/amt-team01/data-object-aws:latest
Error response from daemon: Head "https://ghcr.io/v2/amt-team01/data-object-aws/manifests/latest": unauthorized
```

Je suspecte un problème de droit. Merci de valider.

Nicolas Glassey

**Comment by tomicmario** [comment]
Bonjour @NicolasGlassey ,

Est-ce que votre token est un token classique, et contient les droits suivants ?
![image](https://user-images.githubusercontent.com/58564059/214040443-99fcdc6f-8edd-4867-8b9f-add4d7c0ba85.png)

On ne comprend pas vraiment pourquoi ça ne marche pas. Niveau droit sur le repo, vous devriez théoriquement y avoir accès. On a quand même élevé les droits de Write à Admin, dans le cas où le token est bon.

**Comment by NicolasGlassey** [comment]
@JanisChiffelle  @tomicmario 

Merci d'avoir régit rapidement. Nouvelle tentative ce soir, tout semble ok.

```
docker pull ghcr.io/amt-team01/data-object-aws:latest
latest: Pulling from amt-team01/data-object-aws
6e3729cf69e0: Already exists
4d8d923227d8: Already exists
5834fb29a8c0: Already exists
2dc10fb88481: Already exists
3e829114c90a: Downloading [=======>                                           ]  3.924MB/24.99MB
0eab905a3c6d: Download complete
```
